### ISSUE TITLE
Is this project dead? 

### ISSUE THREAD

**Issue by Zacharybinx34** [crazydevman/mute-profanity#43]
Love the aim of this project, but it doesn't work on latest Kodi builds. Any chance you might update it to work?

**Comment by crazydevman** [comment]
Yes this project is dead, I originally wrote this 10 years ago and a lot has changed since then. But the great thing about open source is that others can take what I've done here and create their own versions as they see fit. A lot of other projects have spawned from this original source. I don't keep track of them all, but if you're looking for something Kodi specific this would be a good place to start: https://forum.kodi.tv/showthread.php?tid=169029
